openapi: 3.1.0
info:
  title: 'API de Carritos'
  version: 1.0.0
  description: 'Documentación para el módulo de carritos.'

paths:
  /api/carts:
    get:
      summary: Obtener todos los carritos
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                - cartId: '1'
                  products: []
                - cartId: '2'
                  products:
                    - productId: '1'
                      quantity: 2

  /api/carts/{cartId}:
    get:
      summary: Obtener un carrito por ID
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                cartId: '1'
                products: []
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              example:
                error: 'Carrito no encontrado'

    post:
      summary: Crear un nuevo carrito
      responses:
        '201':
          description: Creado
          content:
            application/json:
              example:
                cartId: '3'
                products: []

  /api/carts/{cartId}/products/{productId}:
    post:
      summary: Agregar producto al carrito
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        content:
          application/json:
            example:
              quantity: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: 'Producto agregado al carrito exitosamente'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              example:
                error: 'Carrito no encontrado'

    # Continuar con las operaciones de purchaseCart y otras según tus necesidades

components:
  schemas:
    Cart:
      type: object
      properties:
        cartId:
          type: string
          description: ID del carrito
        products:
          type: array
          description: Lista de productos en el carrito
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID del producto en el carrito
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
